// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use environment variables primarily, but provide safe fallback for zero-config Vercel deployment
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://nrzyxussbjcbonsxdcbx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5yenl4dXNzYmpjYm9uc3hkY2J4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU0MTU5MjMsImV4cCI6MjA5MDk5MTkyM30.WXt2ba6HE_OD2TiNqayDCRJCh6CBMBj-u_dBc5a9OYU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});